filegroup(
    name = "models",
    srcs = [
        "//learn_opengl_instanced_rendering/models/planet",
        "//learn_opengl_instanced_rendering/models/rock",
    ],
    visibility = ["//visibility:public"],
)
