filegroup(
    name = "shaders",
    srcs = [
        "1.1.depth_testing.frag",
        "1.1.depth_testing.vert",
        "1.2.single_color.frag",
        "1.3.simple_shader.frag",
        "1.3.simple_shader.vert",
    ],
    visibility = ["//visibility:public"],
)
