cc_library(
    name = "local_paths",
    srcs = [
        "local_paths.cc",
    ],
    hdrs = [
        "executable_path.h",
        "local_paths.h",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "@bazel_tools//tools/cpp/runfiles",
    ],
)
