filegroup(
    name = "textures",
    srcs = [
        "blending_transparent_window.png",
        "grass.png",
        "marble.jpg",
        "metal.png",
    ],
    visibility = ["//visibility:public"],
)
