filegroup(
    name = "textures",
    srcs = [
        "blending_transparent_window.png",
        "container.jpg",
        "grass.png",
        "marble.jpg",
        "metal.png",
        "skybox/back.jpg",
        "skybox/bottom.jpg",
        "skybox/front.jpg",
        "skybox/left.jpg",
        "skybox/right.jpg",
        "skybox/top.jpg",
    ],
    visibility = ["//visibility:public"],
)
