cc_library(
    name = "shaders",
    hdrs = ["shader.h"],
    data = [
        "light_shader.frag",
        "light_shader.vert",
        "shader.frag",
        "shader.vert",
        "simple_shader.frag",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//utils/files",
    ],
)
