filegroup(
    name = "shaders",
    srcs = [
        "explode_geometry_shader.glsl",
        "light_shader.frag",
        "light_shader.vert",
        "normals_geometry_shader.glsl",
        "normals_shader.vert",
        "shader.frag",
        "shader.vert",
        "simple_shader.frag",
        "single_color_shader.frag",
    ],
    visibility = ["//visibility:public"],
)
