filegroup(
    name = "textures",
    srcs = [
        "awesomeface.png",
        "container.jpg",
        "container2.png",
        "container2_specular.png",
    ],
    visibility = ["//visibility:public"],
)
