# hello_triangle/shaders/BUILD
load("//third_party/glsl:defs.bzl", "glsl_shader")

package(default_visibility = ["//hello_triangle:__pkg__"])

glsl_shader(
    name = "vert_shader",
    shader = "shader.vert",
)

glsl_shader(
    name = "frag_shader",
    shader = "shader.frag",
)
