filegroup(
    name = "models",
    srcs = [
        "//learn_opengl_normalmaps/models/backpack",
        "//learn_opengl_normalmaps/models/cyborg",
        "//learn_opengl_normalmaps/models/nanosuit",
    ],
    visibility = ["//visibility:public"],
)
