filegroup(
    name = "assets",
    srcs = [
        "logo.png",
        "logo-inverted.png",
        "logo-no-background-cropped-light-grey.png",
        "logo-no-background-cropped-white.png",
    ],
    visibility = ["//visibility:public"],
)
