cc_library(
    name = "files",
    hdrs = [
        "executable_path.h",
        "file_reader.h",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "@bazel_tools//tools/cpp/runfiles",
    ],
)
