cc_library(
    name = "files",
    hdrs = [
        "file_reader.h",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//utils/local_paths",
        "@bazel_tools//tools/cpp/runfiles",
    ],
)
