cc_library(
    name = "files",
    srcs = [
        "file_reader.cc",
    ],
    hdrs = [
        "file_reader.h",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//utils/local_paths",
    ],
)
