cc_library(
    name = "learn_opengl_utils",
    hdrs = [
        "camera.h",
        "mesh.h",
        "model.h",
        "shader.h",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//third_party/assimp",
        "//third_party/glad",
        "//third_party/stb_image",
        "//utils/files",
        "@glm",
    ],
)
