filegroup(
    name = "backpack",
    srcs = [
        "ao.jpg",
        "backpack.mtl",
        "backpack.obj",
        "diffuse.jpg",
        "normal.png",
        "roughness.jpg",
        "specular.jpg",
    ],
    visibility = ["//visibility:public"],
)
